baseURL = 'https://darkdell.net/'
languageCode = 'en-us'
title = 'Nathan Douglas'
theme = 'hugo-bearcub'
copyright = '2025 Nathan Douglas'

[deployment]
[[deployment.targets]]
cloudFrontDistributionID = 'ERL3QRNQL3Q5K'
name = 'blog'
url = 's3://darkdell.www?region=us-east-1'

[params]
madeWith = "Made with [Bear Cub](https://github.com/clente/hugo-bearcub)"
