baseURL = 'https://blog.hellholt.net/'
languageCode = 'en-us'
title = 'Nathan Douglas'
theme = 'hugo-bearcub'
copyright = '2025 Nathan Douglas'

[params]
madeWith = "Made with [Bear Cub](https://github.com/clente/hugo-bearcub)"

[caches]
[caches.images]
dir = ':cacheDir/images'
